config/routes.rb
HospitalMonteSinai::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "",  :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions', :passwords => 'users/passwords'}, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new' } 

  devise_scope :user do
    get '/login' => 'sessions#login'
    delete '/logout' => 'sessions#destroy'
    post '/usuarios/delete' => 'admin/usuarios#delete'
    get '/register/edit/:id' => 'admin/usuarios#edit'
    post '/usuarios/edit/' => 'admin/usuarios#edit'
  end

  #devise_for :users
  resources :home
  root 'home#index'

  get '/cadastroNewsletter' => 'application#cadastroNewsletter'

  resources :quem_somos
  resources :lamina
  resources :encarte
  resources :lojas
  resources :delivery
  resources :contato
  post 'contato/enviaContato' => 'contato#enviaContato'

  resources :faca_seu_evento
  resources :deli_sazonal
  resources :deli_na_midia
  post 'deli_na_midia/carregaImagens' => 'deli_na_midia#carregaImagens'

  resources :marque_uma_visita
  post 'marque_uma_visita/agendaVisita' => 'marque_uma_visita#marcaVisita'

  resources :novidades, :only => 'index'
  get '/novidades/:id' => 'novidades#index'

  resources :conteudos, :to => 'conteudos#index'
  resources :acontece
  post 'acontece/reserva' => 'acontece#realizaReserva'

  namespace :admin do
    resources :areas
    get 'area/:id' => 'areas#excluiImagemArea'
    get 'area/:id/incluirImagemArea' => 'areas#incluirImagemArea'
    post 'area/areaRepetida' => 'areas#areaRepetida'

    resources :home

    resources :categorias
    get '/categorias/select/:id' => 'categorias#categorias_select'
    get 'categoria/:id' => 'categorias#excluiImagemCategoria'
    get 'categoria/:id/incluirImagemCategoria' => 'categorias#incluirImagemCategoria'

    resources :conteudos
    get 'conteudo/:id' => 'conteudos#excluiImagemConteudo'
    get 'conteudo/:id/excluiImagemConteudoBanner' => 'conteudos#excluiImagemConteudoBanner'

    resources :banners
    get 'banner/:id' => 'banners#excluiImagemBanner'
    get 'banner/excluir/:id' => 'banners#destroy'

    resources :usuarios
    resources :encartes
    get 'encarte/:id' => 'encartes#excluiImagemEncarte'
    get 'encarte/excluiImagemDestaque/:id' => "encartes#excluiImagemDestaque"

    resources :laminas
    get 'lamina/:id' => 'laminas#excluiImagemLamina'
    get 'lamina/excluiImagemDestaque/:id' => "laminas#excluiImagemDestaque"

    resources :lojas
    get 'loja/:id' => 'lojas#excluiImagemLoja'

    resources :deli_sazonals, :controller => 'deli_sazonal'
    get 'deli_sazonal/:id' => 'deli_sazonal#excluiImagemSazonal'

    resources :deli_na_midias
    get 'deli_na_midia/:id' => 'deli_na_midias#excluiImagemMidia'

    resources :novidades
    get 'novidade/:id' => 'novidades#excluiImagemNovidade'
    get 'novidade/excluiImagemNovidadeListagem/:id' => "novidades#excluiImagemNovidadeListagem"

    resources :aconteces
    get 'acontece/:id' => 'aconteces#excluiImagemAcontece'

    resources :listagem_aconteces

  end

end

app/models/admin/encarte.rb
class Admin::Encarte < ActiveRecord::Base

	mount_uploader :imagem_destaque, AttachmentUploader

	has_many :imagens, :class_name => 'Admin::ImagemEncarte', :foreign_key => 'id_encarte'
	
	def self.search(search)  
	    if search  
	      where('nome LIKE ?', "%#{search}%")  
	    else  
	      scoped  
	    end  
  	end 
end

app/controllers/admin/encartes_controller.rb
class Admin::EncartesController < ApplicationController
	
  before_filter :authenticate_user!
  before_action :set_encarte, only: [:show, :edit, :update, :destroy]

  def index
      if params[:search]
        @encartes = Admin::Encarte.all.search(params[:search]).paginate(:per_page => 5, :page => params[:page]).order(sort_column + ' ' + sort_direction)
      else
        @encartes = Admin::Encarte.all.paginate(:per_page => 5, :page => params[:page]).order(sort_column + ' ' + sort_direction)
      end
  end

  def show
  end

  def new
    @encarte = Admin::Encarte.new
    @encartes = Admin::Encarte.all
  end

  def edit
  end

  def create
    @encarte = Admin::Encarte.new(encarte_params)

    respond_to do |format|
        if @encarte.save

        	params[:admin_encarte][:imagem].each do |img|
        		new_img = Admin::ImagemEncarte.new
        		new_img.id_encarte = @encarte.id
        		new_img.imagem = img

        		new_img.save
        	end

          	flash[:notice] = 'Encarte criado com sucesso.'
          	format.html { redirect_to action: 'index'}
          	format.json { render action: 'index', status: :created, location: @encarte }
    	else
          	format.html { render action: 'new' }
          	format.json { render json: @encarte.errors, status: :unprocessable_entity}
        end
      end
  end

  def update
       respond_to do |format|
         if @encarte.update(encarte_params)
          
          unless params[:admin_encarte][:imagem].blank?
              @encarte.imagens.destroy_all

             params[:admin_encarte][:imagem].each do |img|
              new_img = Admin::ImagemEncarte.new
              new_img.id_encarte = @encarte.id
              new_img.imagem = img

              new_img.save
            end
          end

           flash[:notice] = 'Encarte atualizado com sucesso.'
           format.html { redirect_to action: 'index'}
           format.json { head :no_content }
         else
           format.html { render action: 'edit' }
           format.json { render json: @encarte.errors, status: :unprocessable_entity }
         end
       end   
  end

  def excluiImagemDestaque
    img = Admin::Encarte.find(params[:id])
    img.remove_imagem_destaque!

    respond_to do |format|
      if img.update(imagem_destaque: '')
        flash[:notice] = 'Encarte atualizado com sucesso.'
        format.html { redirect_to action: 'index'}
      end
    end
  end

  def excluiImagemEncarte
    img = Admin::ImagemEncarte.find(params[:id])
    img.remove_imagem!

    respond_to do |format|
      if img.destroy
        flash[:notice] = 'Encarte atualizado com sucesso.'
        format.html { redirect_to action: 'edit'}
      end
    end
  end

  def incluirImagemArea
    flash[:notice] = 'Encarte atualizado com sucesso.'
    redirect_to action: 'edit'
  end

  def destroy
    @encarte.imagens.destroy_all
    @encarte.destroy

    respond_to do |format|
      flash[:notice] = 'Encarte excluído com sucesso.'
      format.html { redirect_to action: 'index'}
      format.json { head :no_content }
    end
  end

  private
    def sort_column  
      params[:sort] || "nome"  
    end  
    
    def sort_direction  
      params[:direction] || "asc"  
    end  
    
    def set_encarte
      @encarte = Admin::Encarte.find(params[:id])
    end

    def encarte_params
      params.require(:admin_encarte).permit(:nome, :data_inicio, :data_fim, :status, :imagem, :imagem_destaque)
    end
end

app/controllers/encarte_controller.rb
class EncarteController < ApplicationController
	def index
		@encarte = Admin::Encarte.where('status = 1 AND (data_inicio < NOW() and data_fim > NOW())').order('data_inicio').first()
		render :layout => 'website'
	end
end

app/helpers/admin/encartes_helper.rb
module Admin::EncartesHelper
end

app/helpers/encarte_helper.rb
module EncarteHelper
end

app/views/admin/encartes/_form.html.erb
<%#= stylesheet_link_tag 'bootstrap-datepicker/css/datepicker' %>
<%#= stylesheet_link_tag 'bootstrap-colorpicker/css/colorpicker' %>
<%#= stylesheet_link_tag 'bootstrap-daterangepicker/daterangepicker' %>
<script>

//desaparecer mensagem de erro, sucesso e alerta após 5s
setTimeout(function() {
  $("#conteudo #conteudoPrincipal span.msgSucesso, #conteudo #conteudoPrincipal span.msgErro, #conteudo #conteudoPrincipal span.msgAlerta").fadeOut("slow");
}, 5000);

</script>

	<%= form_for(@encarte, :style => 'form-horizontal') do |f| %>
		
		<div class="form-group">
			<label for="encarte[nome]" class="col-lg-2 col-sm-2 control-label">Nome</label>
			<div class="col-lg-6 col-xs-11">
              	<%= f.text_field :nome, :placeholder => "Nome de exibição do encarte", :class => 'form-control' %>
          	</div>
			  
		</div>
		<div class="clearAll">&nbsp;</div>
 
	  	
		<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Status</label>
			<div class="col-lg-5">
				<%= f.select(:status, [['Não Publicado', '0'],
			                       	   ['Publicado', '1'],
			                           ['Oculto', '2']], {}, { :class => 'form-control' } )%>
			</div>
       	</div>
		<div class="clearAll">&nbsp;</div>

		<div class="form-group">
	    	<label class="col-lg-2 col-sm-2 control-label">Imagem de destaque</label>
	    	<div class="col-lg-8 col-xs-11">
			    <% if @encarte.imagem_destaque.blank? %>
				 	<%= f.file_field :imagem_destaque, :class => 'form-control' %>
				<% else %>
				<div class="project-mask">
			        <div class="thumbnail">
						<%= image_tag("#{@encarte.imagem_destaque}", :class => 'imagemArea') %>
			            <div class="descricao">
							<%= link_to 'Excluir imagem', {:action => "excluiImagemDestaque"}, :id => @encarte.id, :class => 'btnConfirmarNovo btnCancelarNovo btnWidthFixo excluiImagemBanner btn btn-danger' %>	
			            </div>
			        </div>
			    </div>

				<% end %>
			</div>
		</div>
		<div class="clearAll">&nbsp;</div>
		
		<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Imagens do encarte</label>
		    <div class="col-lg-10">
		    	<%@encarte.imagens.each do |img|%>
		    		<div class="project-mask">
				        <div class="thumbnail">
							<%= image_tag(img.imagem, :class => 'imagemArea') %>
				            <div class="descricao">
								<%= link_to 'Excluir imagem', {:action => "excluiImagemEncarte", :id => img.id}, :class => 'btnConfirmarNovo btnCancelarNovo btnWidthFixo excluirImagemArea btn btn-danger' %>	
				            </div>
				        </div>
				    </div>
		    	<%end%>
		 		<%= f.file_field :imagem, :multiple => true, :class => 'inputImportar form-control' %>	
			</div>
	    </div>
				
		<div class="clearAll">&nbsp;</div>

		<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Data Início</label>
		    <div class="col-lg-4 col-xs-11">
			  	<div id="datetimepicker" class="input-group date form_datetime-component datePicker">
			  		<%= if @encarte.data_inicio.blank?
			        		f.text_field :data_inicio, :class=> 'form-control startdate', :size => '16', :value => Time.now.to_datetime.strftime("%d/%m/%Y")
			        	else
			        		f.text_field :data_inicio, :class=> 'form-control startdate', :size => '16', :value => @encarte.data_inicio.try(:strftime, '%d/%m/%Y')
			        	end
			        %>
			        <span class="input-group-btn">
			            <button type="button" class="btn btn-primary date-set"><i class="fa fa-calendar"></i></button>
			        </span>
			    </div>
			</div>
		</div>
		<div class="clearAll">&nbsp;</div>

	  	<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Data Fim</label>
		    <div class="col-lg-4 col-xs-11">
			  	<div id="datetimepicker" class="input-group date form_datetime-component datePicker">

			        <%= if @encarte.data_fim.blank?
			        		f.text_field :data_fim, :class=> 'form-control enddate', :size => '16' 
			        	else
			        		f.text_field :data_fim, :class=> 'form-control enddate', :size => '16', :value => @encarte.data_fim.try(:strftime, '%d/%m/%Y')
			        	end
			        %>
			        <span class="input-group-btn">
			             <button type="button" class="btn btn-primary date-set"><i class="fa fa-calendar"></i></button>
			        </span>
			    </div>
			</div>
		</div>
		<div class="clearAll">&nbsp;</div>

		<div class="divisaoBtnForm">
			<div class="botoesForm botoesFormSaveCancel">
				<%= link_to "Voltar", {:action => "index"}, :class => "btn btn-default" %>
				
				<%= f.submit 'Salvar', :class => 'btn btn-info' %>
			</div>
		</div>
		<%= f.hidden_field :id, :class=> 'form-control' %>
<% end %>

<script>

	$('.thumbnail').hover(function () {
	    $('.descricao', this).stop().animate({
	        bottom: 0
	    }, 200);
	}, function () {
	    $('.descricao', this).stop().animate({
	        bottom: '-100%'
	    }, 200);
	});

	$('.datePicker').datetimepicker({
        format: 'dd/MM/yyyy',
        language: 'pt-BR'
    })

    $("form").validate({
       rules: {
        'admin_encarte[nome]': {
          required: true
        },
        'admin_encarte[data_fim]': {
            greaterThan: ["#admin_encarte_data_inicio"]
        }
      },
      messages: {
        'admin_encarte[nome]': {
         	required: "O nome do encarte é obrigatório."
     	},
     	'admin_encarte[data_fim]':
        { 
            greaterThan:"Data fim menor que data inicio."
        }
      }
  	});


	$.validator.addMethod("greaterThan", 
	function(value, element, params) {
		data_inicial = value.split('/')
        data_inicial = new Date(data_inicial[1]+'-'+data_inicial[0]+'-'+data_inicial[2])

        data_final = $(params).val().split('/')
        data_final = new Date(data_final[1]+'-'+data_final[0]+'-'+data_final[2])

	    if (!/Invalid|NaN/.test(data_inicial)) {
	        return data_inicial > data_final;
	    }

	    return  data_inicial > data_final; 
	},'Data início maior que data fim.');

	$(".enddate").rules('add', { greaterThan: ".startdate" });

</script>

app/views/admin/encartes/_grid.html.erb
<script>
//centralizar paginacao

var a = $('.paginacao a').not('previous_page, next_page').length + 2;
var b = $('.paginacao a').not('previous_page, next_page').outerWidth(true);
var largura_total = (a * b) + 52;
$('.paginacao').width(largura_total);

$('.table th a, .paginacao a').on('click', function () {  
  $.get(this.href, $(this).serialize(), null, 'script');  
  return false;  
}); 

//desaparecer mensagem de erro, sucesso e alerta após 5s
setTimeout(function() {
  $("#conteudo #conteudoPrincipal span.msgSucesso, #conteudo #conteudoPrincipal span.msgErro, #conteudo #conteudoPrincipal span.msgAlerta").fadeOut("slow");
}, 5000);

$(function(){

	//esconder o loader e a máscara caso seja clicado no botão 'não' do modal
	$('body').on('click','button.ui-button:first-child', function() {
		$('span.loader').show();
        $('div.maskLoader').show();
	});
	
	//quando clicar na paginação, exibir loader
    $('.formAddNovo .btn.btn-info, .paginacao a, .table th a').click(function () {
        $('span.loader').show();
        $('div.maskLoader').show();
    });

});

$(document).ready(function(){
	$('.paginacao').show();
})

</script>

<%= hidden_field_tag :direction, params[:direction] %>  
<%= hidden_field_tag :sort, params[:sort] %> 

	<div class="col-lg-12">
		<section class="panel">
			<table class="table table-hover">
				<thead>
					<tr>
				    	<th><%= sortable "nome", "Nome" %></td>
				        <th class="status"><%= sortable "status", "Status" %></td>    	
				        <th>Editar</td>
				        <th>Excluir</td>
					</tr>
				</thead>
				<tbody>
			    <% @encartes.each_with_index do |encarte, index| %>
			      <tr>
			        <td><%= encarte.nome %></td>
			        <td class="status">
						<% case encarte.status %>
						  <%when 0 then %>
						    <%= 'Não publicado' %>
						 <% when 1 then %>
						    <%= 'Publicado' %>
						 <% else %>
						    <%= 'Oculto' %>
						<%end %>
					</td>
					<td>	
						<%= link_to(edit_admin_encarte_path(encarte)) do %>
							<i class="editar fa fa-edit"></i>
						<% end %>
					</td>
					<td>
						<%= button_to '', encarte, method: :delete, 'data-confirm' => 'Tem certeza que deseja excluir esse encarte?', :remote => true, :class => "excluir"  %><i class="fa fa-times"></i>

					</td>
			      </tr>
				  
			    <% end %>
			    </tbody>
			</table>
		</section>	
	</div>

	<div class="divTour">
	<%= will_paginate @encartes,
    	:class => 'paginacao', 
		:previous_label => '<img src="/images/setaPaginacoEsq.png"/>',
		:next_label => '<img src="/images/setaPaginacaoDir.png"/>' 
	%>       
	</div>
          

<script type="text/javascript">

    $('span.loader').hide();
    $('div.maskLoader').hide();

    $('.excluir').click(function(e){
    	if(!confirm('Realmente deseja excluir esse encarte?')){
    		e.preventDefault();
    	}
    });

</script>

app/views/admin/encartes/edit.html.erb
<% content_for :style do -%>
  <%= stylesheet_link_tag 'StyleAreas' %>
  <%= stylesheet_link_tag 'StyleForm' %> 
  <%= stylesheet_link_tag "minimal" %>
  <%= stylesheet_link_tag "select2" %>
  <%= stylesheet_link_tag "StyleCores" %>
  <%= stylesheet_link_tag "spectrum" %>
  <%= stylesheet_link_tag 'bootstrap-datetimepicker.min' %>
<% end -%>

<% content_for :script do -%>
  <%= javascript_include_tag "jquery.icheck.min" %>
  <%= javascript_include_tag "select2.min" %>
  <%= javascript_include_tag "select2_locale_pt-BR" %>
  <%= javascript_include_tag "spectrum" %>
  <%= javascript_include_tag "jquery.validate" %>
  <%= javascript_include_tag "fuelux/js/spinner.min" %>
  <%= javascript_include_tag "bootstrap-datetimepicker.min" %>
<% end -%>

<div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb" style="background: #fff">
                  <li><a href="/admin/home"><i class="fa fa-home"></i> Home</a></li>
                  <li><a href="/admin/encartes">Encartes</a></li>
                  <li class="active"><a href="#">Editar Encarte</a></li>
              </ul>
              <!--breadcrumbs end -->
          </div>
      </div>
    </div>
</div>
<div class="row">
        <div class="col-lg-12">
            <div class="panel">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                      Editar Encarte 
                    </div>
                </div>
                <div class="panel-body">
                  <div class="col-lg-7">
                    <div class="boxForm"><%= render 'form' %></div>
                  </div>
                </div>
            </div>
        </div>
</div>
    
<div class="clearAll">&nbsp;</div>

app/views/admin/encartes/index.html.erb
<% content_for :style do -%>
  <%= stylesheet_link_tag 'StyleAreas' %>
  <%= stylesheet_link_tag 'StyleCores' %>
  <!--gestao-->
  <%= stylesheet_link_tag 'jquery-easy-pie-chart/jquery.easy-pie-chart' %>
  <%= stylesheet_link_tag 'gestao/owl.carousel' %>

<% end -%>
    <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-12">
                  <!--breadcrumbs start -->
                  <ul class="breadcrumb" style="background: #fff">
                      <li><a href="/admin/home"><i class="fa fa-home"></i> Home</a></li>
                      <li class="active"><a href="#">Encartes</a></li>
                  </ul>
                  <!--breadcrumbs end -->
              </div>
          </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel">
                <div class="panel panel-primary">
                    <div class="panel-heading">Lista de encartes
                      <% if can? :manage, :all%>
                        <%= link_to 'Novo encarte', new_admin_encarte_path, :class => 'btn btn-default' %>
                      <% end %>
                    </div>
                </div>
                <div class="panel-body">
                    <!---->
                    <div class="boxForm">
                        
                        <div class="clearAll">&nbsp;</div>
                        
                        <%= if flash[:notice]
                            raw('<div class="alert alert-success fade in msgSucesso"><button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>' + flash[:notice] + '</div>')
                        end %>

                        <div class="formAddNovo">

                            <div class="divTourBusca">
                            <%= form_tag('/admin/encartes', :method => 'get',  :id => "products_search")  do %> 
                                <%= text_field_tag :search, params[:search], :placeholder => "Digite o nome do encarte", :class => 'search1 form-control'%>  
                                <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-info' %>  
                                <% end %>
                            </div>
                            <div class="divTourGrid posRelative">
                                <div id="gridItens">
                                    <div class="row">
                                        <div class="col-lg-12" id="gridItens">
                                          <%= render 'grid' %>

                                        </div>    
                                    </div>
                                </div>
                                <div class="maskLoader"></div>
                            </div>
                            
                            
                            <div class="clearAll">&nbsp;</div>
                        </div>
                    </div>
                    <span class="loader"><img src="/images/loaderHand.gif" /></span>
                    <!---->
                </div>
            </div>
        </div> 
        
    </div>

app/views/admin/encartes/index.js.erb
$('#gridItens').html('<%= escape_javascript(render("grid")) %>');  

app/views/admin/encartes/new.html.erb
<% content_for :style do -%>
  <%= stylesheet_link_tag 'StyleAreas' %>
  <%= stylesheet_link_tag 'StyleForm' %> 
  <%= stylesheet_link_tag "minimal" %> <!-- Checkbox Estilizado -->
  <%= stylesheet_link_tag "select2" %> <!-- DropDown Estilizado -->
  <%= stylesheet_link_tag "StyleCores" %>
  <%= stylesheet_link_tag "spectrum" %> <!-- ColorPicker -->
  <%= stylesheet_link_tag 'bootstrap-datetimepicker.min' %>
<% end -%>

<% content_for :script do -%>
  <%= javascript_include_tag "jquery.icheck.min" %> <!-- Checkbox Estilizado -->
  <%= javascript_include_tag "select2.min" %> <!-- DropDown Estilizado -->
  <%= javascript_include_tag "select2_locale_pt-BR" %> <!-- DropDown Estilizado -->
  <%= javascript_include_tag "jquery.validate" %> <!-- Validação dos campos -->
  <%= javascript_include_tag "spectrum" %> <!-- ColorPicker -->
  <%= javascript_include_tag "fuelux/js/spinner.min" %>
  <%#= javascript_include_tag "gestao/advanced-form-components.js" %>
  <%= javascript_include_tag "bootstrap-datetimepicker.min" %>
<% end -%>




<div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb" style="background: #fff">
                  <li><a href="/admin/home"><i class="fa fa-home"></i> Home</a></li>
                  <li><a href="/admin/encartes">Encartes</a></li>
                  <li class="active"><a href="#">Novo encarte</a></li>
              </ul>
              <!--breadcrumbs end -->
          </div>
      </div>
    </div>
</div>
<div class="row">
        <div class="col-lg-12">
            <div class="panel">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                      Novo encarte
                    </div>
                </div>
                <div class="panel-body">
                  <div class="col-lg-7">
                    <div class="boxForm"><%= render 'form' %></div>
                  </div>
                </div>
            </div>
        </div>
</div>
    
<div class="clearAll">&nbsp;</div>