config/routes.rb
HospitalMonteSinai::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "",  :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions', :passwords => 'users/passwords'}, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new' } 

  devise_scope :user do
    get '/login' => 'sessions#login'
    delete '/logout' => 'sessions#destroy'
    post '/usuarios/delete' => 'admin/usuarios#delete'
    get '/register/edit/:id' => 'admin/usuarios#edit'
    post '/usuarios/edit/' => 'admin/usuarios#edit'
  end

  #devise_for :users
  resources :home
  root 'home#index'

  get '/cadastroNewsletter' => 'application#cadastroNewsletter'

  resources :quem_somos
  resources :lamina
  resources :encarte
  resources :lojas
  resources :delivery
  resources :contato
  post 'contato/enviaContato' => 'contato#enviaContato'

  resources :faca_seu_evento
  resources :deli_sazonal
  resources :deli_na_midia
  post 'deli_na_midia/carregaImagens' => 'deli_na_midia#carregaImagens'

  resources :marque_uma_visita
  post 'marque_uma_visita/agendaVisita' => 'marque_uma_visita#marcaVisita'

  resources :novidades, :only => 'index'
  get '/novidades/:id' => 'novidades#index'

  resources :conteudos, :to => 'conteudos#index'
  resources :acontece
  post 'acontece/reserva' => 'acontece#realizaReserva'

  namespace :admin do
    resources :areas
    get 'area/:id' => 'areas#excluiImagemArea'
    get 'area/:id/incluirImagemArea' => 'areas#incluirImagemArea'
    post 'area/areaRepetida' => 'areas#areaRepetida'

    resources :home

    resources :categorias
    get '/categorias/select/:id' => 'categorias#categorias_select'
    get 'categoria/:id' => 'categorias#excluiImagemCategoria'
    get 'categoria/:id/incluirImagemCategoria' => 'categorias#incluirImagemCategoria'

    resources :conteudos
    get 'conteudo/:id' => 'conteudos#excluiImagemConteudo'
    get 'conteudo/:id/excluiImagemConteudoBanner' => 'conteudos#excluiImagemConteudoBanner'

    resources :banners
    get 'banner/:id' => 'banners#excluiImagemBanner'
    get 'banner/excluir/:id' => 'banners#destroy'

    resources :usuarios
    resources :encartes
    get 'encarte/:id' => 'encartes#excluiImagemEncarte'
    get 'encarte/excluiImagemDestaque/:id' => "encartes#excluiImagemDestaque"

    resources :laminas
    get 'lamina/:id' => 'laminas#excluiImagemLamina'
    get 'lamina/excluiImagemDestaque/:id' => "laminas#excluiImagemDestaque"

    resources :lojas
    get 'loja/:id' => 'lojas#excluiImagemLoja'

    resources :deli_sazonals, :controller => 'deli_sazonal'
    get 'deli_sazonal/:id' => 'deli_sazonal#excluiImagemSazonal'

    resources :deli_na_midias
    get 'deli_na_midia/:id' => 'deli_na_midias#excluiImagemMidia'

    resources :novidades
    get 'novidade/:id' => 'novidades#excluiImagemNovidade'
    get 'novidade/excluiImagemNovidadeListagem/:id' => "novidades#excluiImagemNovidadeListagem"

    resources :aconteces
    get 'acontece/:id' => 'aconteces#excluiImagemAcontece'

    resources :listagem_aconteces

  end

end

app/models/admin/categoria.rb
class Admin::Categoria < ActiveRecord::Base  
  mount_uploader :imagem, AttachmentUploader

  has_many :conteudos, :class_name => 'Admin::Conteudo', :dependent => :restrict_with_error
  
  belongs_to :area, :class_name => 'Admin::Area'

  belongs_to :categoria, :class_name => 'Admin::Categoria'

  has_many :categorias, :class_name => 'Admin::Categoria', :foreign_key => "categoria_id", :dependent => :restrict_with_error



  def self.search(search)  
    if search  
      where('nome LIKE ?', "%#{search}%")  
    else  
        scoped  
    end  
  end
end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < ApplicationController
  before_filter :authenticate_user!
  #load_and_authorize_resource
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @categorias = Admin::Categoria.all.search(params[:search]).paginate(:per_page => 5, :page => params[:page]).order(sort_column + ' ' + sort_direction)
    else
      @categorias = Admin::Categoria.all.paginate(:per_page => 5, :page => params[:page]).order(sort_column + ' ' + sort_direction)
    end
  end

  def categorias_select
       area = Admin::Area.find(params[:area_id])
       @categorias = area.categorias.find(:all, :conditions => ['id <> ?', params[:categoria_id]]).map{|c| [c.nome, c.id]}.insert(0, "Sem categoria pai")
  end
  
  
  def show
  end

  def new
    @categoria = Admin::Categoria.new
    @categorias = Admin::Categoria.all
  end


  def edit
    @categorias = Admin::Categoria.select("id, nome").where("id <> ?", params[:id])
  end
  
  def excluiImagemCategoria
    @categoria = Admin::Categoria.find(params[:id])
    @categoria.remove_imagem!
    @categoria.imagem_url = ''
    @categoria.imagem_target_link = ''
    
    respond_to do |format|
      if @categoria.update(params[:categoria])
        flash[:notice] = 'Categoria atualizada com sucesso.'
        format.html { redirect_to action: 'edit'}
      end
    end
  end
  
  
  def create
    @categoria = Admin::Categoria.new(categoria_params)
      respond_to do |format|
        if @categoria.save
          atualizaOrdem(@categoria.id, @categoria.ordem)
          flash[:notice] = 'Categoria criada com sucesso.'
          format.html { redirect_to action: 'index'}
          format.json { render action: 'index', status: :created, location: @categoria }
        else
          format.html { render action: 'new' }
          format.json { render json: @categoria.errors, status: :unprocessable_entity }
        end
      end
  end
  

  def update
      respond_to do |format|
         if @categoria.update(categoria_params)
          atualizaOrdem(@categoria.id, @categoria.ordem)
           flash[:notice] = 'Categoria atualizada com sucesso.'
           format.html { redirect_to action: 'index'}
           format.json { head :no_content }
         else
           format.html { render action: 'edit' }
           format.json { render json: @categoria.errors, status: :unprocessable_entity }
         end
       end
  end
  
  def atualizaOrdem id_categoria, ordem_categoria
    update_categoria = Admin::Categoria.where("id <> ? AND (ordem = ?)", id_categoria, ordem_categoria).first
    unless update_categoria.blank?
      update_categoria.update(ordem: update_categoria.ordem + 1)
      atualizaOrdem(update_categoria.id, update_categoria.ordem)
    end
  end 

  def destroy
    if @categoria.destroy       
      respond_to do |format|
        flash[:notice] = 'Categoria excluída com sucesso.'
        format.html { redirect_to action: 'index'}
        format.json { head :no_content }
      end
    else      
      if Admin::Categoria.exists?(categoria_id: @categoria.id) 
        respond_to do |format|
          flash[:notice] = 'Não foi possível excluir a categoria pois ela possui outras categorias relacionadas.'
          format.html { redirect_to action: 'index' }
          format.json { head :no_content }
        end
      elsif Admin::Conteudo.exists?(:categoria_id => @categoria.id)
        respond_to do |format|
          flash[:notice] = 'Não foi possível excluir a categoria pois ela possui outras categorias relacionadas.'
          format.html { redirect_to action: 'index' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          flash[:notice] = 'Ocorreu um erro ao excluir a categoria. Tente novamente.'
          format.html { redirect_to action: 'index' }
          format.json { head :no_content }
        end 
      end
    end
  end
  
  private
    def sort_column  
      params[:sort] || "ordem"  
    end  
    
    def sort_direction  
      params[:direction] || "asc"  
    end  
    
    def set_categoria
      @categoria = Admin::Categoria.find(params[:id])
    end

    def categoria_params
      params.require(:admin_categoria).permit(:nome, :url, :target_url, :ordem, :status, :categoria_id, :area_id, :imagem, :imagem_url, :imagem_target_link)
    end
    
end

app/helpers/admin/categorias_helper.rb
module Admin::CategoriasHelper
end

app/views/admin/categorias/_form.html.erb
<div class="formAddNovo novaAreaWidth ">
	
	<%= form_for(@categoria, :class=> 'form-horizontal') do |f| %>
		
	    <%= f.hidden_field :url, :id => 'urlDestinoCategorias', :value => "http://#{request.host_with_port}/categorias/" %>
		
		<%= f.hidden_field :id, :id => 'idCategoria', :value => @categoria.id %>

		<div class="form-group">
			<label class="col-lg-2 col-sm-2 control-label">Área</label>
			<div class="col-lg-6 col-xs-11">
				<%= f.select(:area_id, Admin::Area.all.collect {|a| [ a.nome, a.id ] }, { :include_blank => false }, :id => 'nomeArea', :style=> 'width: 100%') %>
			</div>
		</div>
		    <div class="clearAll">&nbsp;</div>
			
		<div class="form-group">
			<label class="col-lg-2 col-sm-2 control-label">Categoria pai</label>
			<div class="col-lg-6 col-xs-11">
				<%= f.select(:categoria_id, @categorias.map {|c| [ c.nome, c.id ] }, { :include_blank => "Sem categoria pai" }, :id => 'nomeCategoriaPai', :style=> 'width: 100%') %>
			</div>
		</div>
			<div class="clearAll">&nbsp;</div>
		
		<div class="form-group">
			<label for="categoria[nome]" class="col-lg-2 col-sm-2 control-label">Nome</label>
		    <div class="col-lg-6 col-xs-11">
                <%= f.text_field :nome, :placeholder => "Nome de exibição da categoria", :class => 'form-control' %>		
              </div>
		</div>
		<div class="clearAll">&nbsp;</div>
	  
		<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Ordem</label>
		    <div class="col-lg-10">
			    <div id="ordem">
	              <div class="input-group input-small">
	                
	                  <%= if @categoria.url.blank?
				 		 f.text_field :ordem, :min => 1, :value => @categorias.count + 1, :class => 'spinner-input form-control'  
			 		  else
					     f.text_field :ordem, :min => 1, :class => 'spinner-input form-control'
					  end %>
	                  <div class="spinner-buttons input-group-btn btn-group-vertical">
	                      <button type="button" class="btn spinner-up btn-xs btn-default">
	                          <i class="fa fa-angle-up"></i>
	                      </button>
	                      <button type="button" class="btn spinner-down btn-xs btn-default">
	                          <i class="fa fa-angle-down"></i>
	                      </button>
	                  </div>
	              </div>
	          	</div>
	        </div>
		</div>
			<div class="clearAll">&nbsp;</div>
	  
	  	<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Url da categoria</label>
		    <div class="col-lg-6 col-xs-11">
		    	<%= if @categoria.url.blank?
			 		f.text_field :url, :value => "http://#{request.host_with_port}/categorias/" , :class=> 'form-control'
		 		else
					f.text_field :url, :class=> 'form-control'
				end %>
			</div>
		</div>
			<div class="clearAll">&nbsp;</div>
		
		<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Abrir em</label>
			<div class="col-lg-5 col-xs-11">
				<%= f.select(:target_url, [['Na mesma janela', '_self'],
			                       ['Em uma nova janela', '_blank']], {}, { :class => 'form-control', })%>
			</div>
		</div>
		<div class="clearAll">&nbsp;</div>
		
		<div class="form-group">
		    <label class="col-lg-2 col-sm-2 control-label">Status</label>
			<div class="col-lg-6 col-xs-11">
				<%= f.select(:status, [['Não publicado', '0'],
			                       ['Publicado', '1'],
			                       ['Oculto', '2']], {}, { :class => 'form-control' } )%>
			</div>                       
       	</div>
		<div class="clearAll">&nbsp;</div>

		<div style="display:none">
		<!---------------------------->
				<div class="form-group">
				    <span>Imagem</span>
				    <% if @categoria.imagem.blank? %>
					 		<%= f.file_field :imagem, :class => 'inputImportar' %>
							
							<%= f.submit 'Importar', :class => "btnCriarNovo btnImportar"%>
							
			 		<% else %>
						<div class="project-mask">
					        <div class="thumbnail">
								<%= image_tag("#{@categoria.imagem}", :class => 'imagemArea') %>
					            <div class="descricao">
						
									<%= link_to 'Excluir imagem', {:action => "excluiImagemCategoria"}, :id => @categoria.id, :class => 'btnConfirmarNovo btnCancelarNovo btnWidthFixo excluirImagemArea' %>
											
					            </div>
					        </div>
					    </div>
				</div>
				<div class="clearAll">&nbsp;</div>
				<div data-intro='Aqui você pode inserir um link para quando o usário clicar na imagem.' data-step='9' data-position='top' class="divTour">
				    <span>Imagem Url</span>
				    <%= f.text_field :imagem_url, :placeholder => "Link da imagem de destaque" %>
				</div>
						<div class="clearAll">&nbsp;</div>
				
				<div data-intro='E escolher como ele será aberto, em uma nova ou na mesma janela.' data-step='10' data-position='top' class="divTour divTourDrop">
					    <span>Target</span>
						<%= f.select(:imagem_target_link, [['Abrir em nova janela', '_blank'],
						                       ['Abrir na mesma janela', '_self']], {}, { :class => 'dropDownEstilizado' } )%>
											   
					<% end %>
				</div>
				<div class="clearAll">&nbsp;</div>
			<!---------------------------->	
		</div>
</div>

<div class="divisaoBtnForm col-lg-8">
	<div class="botoesForm botoesFormSaveCancel">
		<%= link_to "Voltar", {:action => "index"}, :class => "btn btn-default" %>
		
		<%= f.submit 'Salvar', :class => 'btn btn-info' %>
	</div>
</div>
<% end %>

<script>
	$('#ordem').spinner();
	$('#nomeArea').select2();
	$('#nomeCategoriaPai').select2();

	var urlCategoria = $( "#categoria_url" ).val();
	var urlDestino = $( "#urlDestinoCategorias" ).val();
	
	$( "#categoria_nome" ).keyup(function( event ) {
		if ($( "#categoria_url" ).val().indexOf(urlCategoria) >= 0)
		{
			var value = urlDestino + $( "#categoria_nome" ).val().replace(/\s/g, '+');
			$( "#categoria_url" ).val( value );
			
			urlCategoria = $( "#categoria_url" ).val();
		}
	});
	
	$('.thumbnail').hover(function () {
	    $('.descricao', this).stop().animate({
	        bottom: 0
	    }, 200);
	}, function () {
	    $('.descricao', this).stop().animate({
	        bottom: '-100%'
	    }, 200);
	});
	
	$('#admin_categoria_area_id').change(function() {
		$.ajax({
	        url: "/admin/categorias/select/1?area_id=" + $('#admin_categoria_area_id').val() + '&categoria_id=' + $('#idCategoria').val(),
	        dataType: "script"
	    });
	});

  	$.ajax({
  		url: "/admin/categorias/select/1?area_id=" + $('#admin_categoria_area_id').val() + '&categoria_id=' + $('#idCategoria').val(),
  	    dataType: "script"
  	});


</script>
<script type="text/javascript">
  $(document).ready(function () {
  		//button customizado
	    $('.botoesCustom input').iCheck({
	        checkboxClass: 'icheckbox_minimal',
	        increaseArea: '20%' // optional
	    });

	   

	    //color picker do titulo
        

		//Validação do formulário
    	$("form.edit_admin_categoria, form.new_admin_categoria").validate({
           rules: {
            'admin_categoria[nome]': 
            {
              required: true
            }
          },
          messages: {
            'admin_categoria[nome]': {
             	required: "O nome da categoria é obrigatório."
         	}
          }
      	});

  	});
 
</script>
  

app/views/admin/categorias/_grid.html.erb
<script>
//centralizar paginacao
var a = $('.paginacao a').not('previous_page, next_page').length + 2;
var b = $('.paginacao a').not('previous_page, next_page').outerWidth(true);
var largura_total = (a * b) + 52;
$('.paginacao').width(largura_total);

$('.table th a, .paginacao a').on('click', function () {  
  $.get(this.href, $(this).serialize(), null, 'script');  
  return false;  
}); 

//desaparecer mensagem de erro, sucesso e alerta após 5s
setTimeout(function() {
  $("#conteudo #conteudoPrincipal span.msgSucesso, #conteudo #conteudoPrincipal span.msgErro, #conteudo #conteudoPrincipal span.msgAlerta").fadeOut("slow");
}, 5000);

$(function(){

	//esconder o loader e a máscara caso seja clicado no botão 'não' do modal
	$('body').on('click','button.ui-button:first-child', function() {
		$('span.loader').show();
        $('div.maskLoader').show();
	});
	
	//quando clicar na paginação, exibir loader
    $('.formAddNovo .btn.btn-info, .paginacao a, .table th a').click(function () {
        $('span.loader').show();
        $('div.maskLoader').show();
    });

});
$(document).ready(function(){
	$('.paginacao').show();
})

</script>

<%= hidden_field_tag :direction, params[:direction] %>  
<%= hidden_field_tag :sort, params[:sort] %> 

<div class="col-lg-12">
		<section class="panel">
			<table class="table table-hover">
			<thead>
				<tr class="tabelaHeader">
			    	<th><%= sortable "nome", "Nome" %></td>
			        <th class="cat_pai"><%= sortable "categoria_id", "Categoria pai" %></td>
			        <th class="url"><%= sortable "url", "Url" %></td>
			        <th class="ordem"><%= sortable "ordem", "Ordem" %></td>
			        <th class="status"><%= sortable "status", "Status" %></td>
			        <th>Editar</td>
			        <th>Excluir</td>
			    </tr>
			</thead>
			<tbody>    
			    <% @categorias.each_with_index do |categoria, index| %>
			      <tr class="<%= cycle("", "alternate") %>">
			        <td class="cat_pai"><%= categoria.nome %></td>
			        <td>
			        	<%= 
			        	if categoria.categoria.blank?
			        		"-"
			        	else
			        		categoria.categoria.nome
			        	end
			        	 %>
					</td>
			        <td class="url"><%= 
						if categoria.url.exclude? "http://#{request.host_with_port}"
							categoria.url
						else 
							categoria.url.at(21..-1).truncate(25) 
						end %>
					
					</td>
			        <td class="ordem"><%= categoria.ordem %></td>
			        <td class="status">
						<% case categoria.status %>
						  <%when 0 then %>
						    <%= 'Não publicado' %>
						 <% when 1 then %>
						    <%= 'Publicado' %>
						 <% else %>
						    <%= 'Oculto' %>
						<%end %>
					</td>
			        
					<td>
						<%= link_to(edit_admin_categoria_path(categoria)) do %>
							<i class="fa fa-edit"></i>
						<% end %>
					</td>

					<td>
						<%= button_to '', categoria, method: :delete, 'data-confirm' => 'Tem certeza que deseja excluir essa categoria?', :remote => true, :class => "excluir"  %>
						<i class="fa fa-times"></i>
					</td>
			      </tr>
				  
			    <% end %>
			</tbody>    
			</table>
		</section>
</div>

<div>
	<%= will_paginate @categorias,
    	:class => 'paginacao', 
		:previous_label => '<img src="/images/setaPaginacaoEsq.png"/>',
		:next_label => '<img src="/images/setaPaginacaoDir.png"/>' 
	%>                  
</div>

<script type="text/javascript">

    $('span.loader').hide();
    $('div.maskLoader').hide();
    $('.excluir').click(function(e){
    	if(!confirm('Realmente deseja excluir essa categoria?')){
    		e.preventDefault();
    	}
    });

</script>

app/views/admin/categorias/categorias_select.js.erb
$('#categorias_select').html("<%= escape_javascript(options_for_select(@categorias)) %>");
 

app/views/admin/categorias/edit.html.erb
<% content_for :style do -%>
  <%= stylesheet_link_tag 'StyleAreas' %>
  <%= stylesheet_link_tag 'StyleForm' %> 
  <%= stylesheet_link_tag "minimal" %>
  <%= stylesheet_link_tag "select2.min" %>
  <%= stylesheet_link_tag "StyleCores" %>
  <%= stylesheet_link_tag "spectrum" %>
<% end -%>

<% content_for :script do -%>
  <%= javascript_include_tag "jquery.icheck.min" %>
  <%= javascript_include_tag "select2.min" %>
  <%= javascript_include_tag "select2_locale_pt-BR" %>
  <%= javascript_include_tag "spectrum" %>
  <%= javascript_include_tag "jquery.validate" %>
  <%= javascript_include_tag "fuelux/js/spinner.min" %>
<% end -%>

<div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb" style="background: #fff">
                  <li><a href="/admin/home"><i class="fa fa-home"></i> Home</a></li>
                  <li><a href="/admin/categorias">Categorias</a></li>
                  <li class="active"><a href="#">Editar categoria</a></li>
              </ul>
              <!--breadcrumbs end -->
          </div>
      </div>
    </div>
</div>
<div class="row">
        <div class="col-lg-12">
            <div class="panel">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                      Editar Categoria
                    </div>
                </div>
                <div class="panel-body">
                  <div class="col-lg-7">
                    <div class="boxForm"><%= render 'form' %></div>
                  </div>
                </div>
            </div>
        </div>
</div>
    
<div class="clearAll">&nbsp;</div>

app/views/admin/categorias/index.html.erb
<% content_for :style do -%>
  <%= stylesheet_link_tag 'StyleAreas' %>
  <%= stylesheet_link_tag "StyleCores" %>
<% end -%>


    <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-12">
                  <!--breadcrumbs start -->
                  <ul class="breadcrumb" style="background: #fff">
                      <li><a href="/admin/home"><i class="fa fa-home"></i> Home</a></li>
                      <li class="active"><a href="#">Categorias</a></li>
                  </ul>
                  <!--breadcrumbs end -->
              </div>
          </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel">
                <div class="panel panel-primary">
                    <div class="panel-heading">Lista de categorias <%= link_to 'Nova categoria', new_admin_categoria_path, :class => 'btn btn-default' %></div>
                </div>
                <div class="panel-body">
                    <!---->
                    <div class="boxForm">
                        
                        <div class="clearAll">&nbsp;</div>
                        
                        <%= if flash[:notice]  
                             raw('<div class="alert alert-success fade in msgSucesso"><button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>' + flash[:notice] + '</div>')
                        end %>

                        <div class="formAddNovo">

                            <div class="divTourBusca">
                                <%= form_tag('/admin/categorias', :method => 'get',  :id => "products_search")  do %> 
                                    <%= text_field_tag :search, params[:search], :placeholder => "Digite o nome da categoria", :class => 'search1 form-control'%>  
                                    <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-info' %>  
                                    <% end %>
                            </div>
                            <div  class="divTourGrid posRelative">
                                <div id="gridItens">
                                    <div class="row">
                                        <div class="col-lg-12">
                                          <%= render 'grid' %>
                                        </div>    
                                    </div>
                                </div>
                                <div class="maskLoader"></div>
                             </div>
                            
                            
                            <div class="clearAll">&nbsp;</div>
                        </div>
                    </div>
                    <span class="loader"><img src="/images/loaderHand.gif" /></span>
                    <!---->
                </div>
            </div>
        </div>
    </div>
        
	

app/views/admin/categorias/index.js.erb
$('#gridItens').html('<%= escape_javascript(render("grid")) %>');  

app/views/admin/categorias/new.html.erb
<% content_for :style do -%>
  <%= stylesheet_link_tag 'StyleAreas' %>
  <%= stylesheet_link_tag 'StyleForm' %> 
  <%= stylesheet_link_tag "minimal" %> <!-- Checkbox Estilizado -->
  <%= stylesheet_link_tag "select2.min" %> <!-- DropDown Estilizado -->
  <%= stylesheet_link_tag "StyleCores" %>
  <%= stylesheet_link_tag "spectrum" %> <!-- ColorPicker -->
<% end -%>

<% content_for :script do -%>
  <%= javascript_include_tag "jquery.icheck.min" %> <!-- Checkbox Estilizado -->
  <%= javascript_include_tag "select2.min" %> <!-- DropDown Estilizado -->
  <%= javascript_include_tag "select2_locale_pt-BR" %> <!-- DropDown Estilizado -->
  <%= javascript_include_tag "spectrum" %> <!-- ColorPicker -->
  <%= javascript_include_tag "jquery.validate" %> <!-- Validação dos campos -->
  <%= javascript_include_tag "fuelux/js/spinner.min" %>
<% end -%>

<div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb" style="background: #fff">
                  <li><a href="/admin/home"><i class="fa fa-home"></i> Home</a></li>
                  <li><a href="/admin/categorias">Categorias</a></li>
                  <li class="active"><a href="#">Nova categoria</a></li>
              </ul>
              <!--breadcrumbs end -->
          </div>
      </div>
    </div>
</div>
<div class="row">
        <div class="col-lg-12">
            <div class="panel">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                      Nova Categoria
                    </div>
                </div>
                <div class="panel-body">
                  <div class="col-lg-7">
                    <div class="boxForm"><%= render 'form' %></div>
                  </div>
                </div>
            </div>
        </div>
</div>
    
<div class="clearAll">&nbsp;</div>